### ISSUE TITLE
Single Lap SC and Single Lap NonSC are similar

### ISSUE THREAD

**Issue by Jean-Rubin** [benediktclaus/tidytuesday-mario-kart#1]
The record entries have similar rows for Single Lap SC and Single Lap NonSC (same date, same period and same time).

I think the problem comes from the url generation part where the script generate similar url for non shortcut and shortcut world record, and thus scrape identical tables.

**Comment by cait-csv** [comment]
I assume `records` (in `drivers` dataset) is the number of world records the player held in that given year and `total` is the sum of `records` held since 1997. 

Would that mean `records` (in `drivers` dataset) should match the total count of the respective players from the `records` dataset? 

When I isolate `records` dataset to only 1998, the total count for Penev was 225 (`records` dataset) vs 181 `records` (shown in `drivers` dataset). So I just wanna check.

**Comment by benediktschfr** [comment]
@Jean-Rubin was right, the URLs for scraping single lap short cut records were wrong. I fixed the issue in 90e01a112ee146e18932b1044ec5b2400eea2856
